# Generated by Django 4.1.5 on 2023-01-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rating',
            field=models.CharField(default='exit', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='review',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
